### PR TITLE
Upgrade optimism/op-geth dependencies, add test that calls eth_getLogs

### PR DESCRIPTION
**Pull request by mslipper**
* Update op-geth to ensure it runs the latest images
* Enable Regolith
* Update module references to use the new single-module go structure from monorepo
* Set op-geth log level based on the `-sim.loglevel` option to match how other clients work
* rpc sim previously only ran one of the tests repeatedly rather than actually running each test
* Fix deployContractOutOfGas to not expect the tx to both succeed and fail (it should fail)
* Add a new test for eth_getLogs method
* Use an unfunded account when performing eth_call in `callContractTest` so it fails if any gas charges are incorrectly applied

### CODE REVIEW

**Comment by ajsutton** [comment]
New test looks good but there seem to be some compile issues in `generate` - looks related to withdrawals being added primarily. Given the time there I can take a look at fixing it.

**Comment by mslipper** [comment]
🙏 thanks Adrian!

**Comment by mslipper** [comment]
Yep, looks like this is catching the `eth_call` issue.

**Comment by ajsutton** [comment]
Awesome and with a local build of https://github.com/ethereum-optimism/op-geth/pull/67 the tests all pass. 🎉

**Comment by mslipper** [comment]
@ajsutton one bug I found in here is that Regolith is not activated in the devnet - just running some last tests of both https://github.com/ethereum-optimism/op-geth/pull/67 and what we have now to make sure things fail.

**Comment by ajsutton** [comment]
Ah that would explain it. I was just testing without the eth_getLogs fix in op-geth and was trying to work out why it wasn't failing.  Not having regolith would do it.

**Review by protolambda — APPROVED** [review]

**Pull request merged**
