### PR TITLE
Add simple ERC20 bindings

### PR DESCRIPTION
**Pull request by mslipper**
This enables ERC20 deposit/withdrawal tests.

### CODE REVIEW

**Review by protolambda — COMMENTED** [review]
Don't we already have ERC20 bindings in the monorepo? https://github.com/ethereum-optimism/optimism/blob/7d6cca224f651d2b93a06fdf33a6e7c2a210ed2a/op-bindings/bindings/erc20.go#L122

**Comment by maurelian** [comment]
~~I don't love having a `./contracts` dir in the root. It's likely to misdirect/confuse visitors. If it is needed, could it be renamed or relocated?~~
LOL nvm, just realized I'm not in the monorepo.

**Comment by mslipper** [comment]
The implementation in the monorepo does not contain any token-creation functionality, since it just exports the base OZ ERC20. This one mints tokens in the constructor, which makes testing easier since I can just send tokens from the deployer.

**Review by trianglesphere — APPROVED** [review]

**Comment by mslipper** [comment]
FYI @protolambda I'm going to merge this since I need a commit on Optimism to update dependencies. Let me know if you'd like me to revisit this solution, happy to do so on a separate PR.

**Pull request merged**
